version: "3"

# volumes:
  # fuseki_storage:

services:

  api:
    build:
      context: api
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    working_dir: /code
    volumes:
      - ./api/app:/code/app
    environment:
      - TRIPLESTORE_URL
      - DATASET_NAME
      - JWKS_URL
      - JWT_AUD
    networks:
      - marketplace

  fuseki:
    build:
      context: fuseki
      dockerfile: Dockerfile
    # volumes:
      # - fuseki_storage:/fuseki-base/databases
    ports:
      - 3030:3030
    networks:
      - marketplace
      
networks:
  marketplace:
    name: marketplace