PREFIX adms: <https://www.w3.org/ns/adms#>
PREFIX dcat: <http://www.w3.org/ns/dcat#>
PREFIX dct: <http://purl.org/dc/terms/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX vcard: <http://www.w3.org/2006/vcard/ns#>
PREFIX uk_cross_government_metadata_exchange_model: <https://w3id.org/co-cddo/uk-cross-government-metadata-exchange-model/> 
PREFIX skos: <http://www.w3.org/2004/02/skos/core#> 
PREFIX cddo_asset: <http://marketplace.cddo.gov.uk/asset/>
PREFIX cddo_graph: <http://marketplace.cddo.gov.uk/graph/>

SELECT ?resourceUri ?updateFrequency ?endpointDescription ?endpointURL ?serviceStatus ?serviceType ?accessRights
?contactName ?contactEmail ?contactAddress ?contactTelephone ?created ?description ?issued
?licence ?modified ?organisation ?securityClassification ?summary ?title ?type ?version ?catalogueCreated ?catalogueModified ?creator ?keyword ?alternativeTitle ?relatedAssets ?theme ?servesDataset ?distribution ?externalIdentifier
FROM cddo_graph:assets
WHERE {{
?resourceUri dct:identifier "$asset_id" ;
   dcat:contactPoint ?contact ;
   dct:description ?description ;
   dct:license ?licence ;
   dct:publisher ?organisation ;
   uk_cross_government_metadata_exchange_model:securityClassification ?securityClassification ;
   dct:title ?title ;
   a ?typeURI;
   dcat:version ?version ;
   cddo_asset:created ?catalogueCreated ;
   cddo_asset:modified ?catalogueModified .
  ?typeURI rdfs:label ?type .
  OPTIONAL {{ ?resourceUri dct:accrualPeriodicity ?freq }
            { ?freq rdfs:label ?updateFrequency }} .
  OPTIONAL {{ ?resourceUri dcat:distribution ?distribution }}.
  OPTIONAL {{ ?resourceUri dcat:endpointDescription ?endpointDescription }}.
  OPTIONAL {{ ?resourceUri dcat:endpointURL ?endpointURL }}.
  OPTIONAL {{ ?resourceUri dcat:servesDataset ?servesDataset }} .
  OPTIONAL {{ ?resourceUri adms:status ?serviceStatus }} .
  OPTIONAL {{ ?resourceUri dct:type ?serviceType }} .
  OPTIONAL {{ ?resourceUri dct:accessRights ?accessRights }} .
  OPTIONAL {{ ?resourceUri dct:created ?created }} .
  OPTIONAL {{ ?resourceUri dct:issued ?issued }} .
  OPTIONAL {{ ?resourceUri dct:modified ?modified }} .
  OPTIONAL {{ ?resourceUri rdfs:comment ?summary }} .
  OPTIONAL {{ ?resourceUri dct:creator ?creator }} .
  OPTIONAL {{ ?resourceUri dcat:keyword ?keyword }} .
  OPTIONAL {{ ?resourceUri dct:alternative ?alternativeTitle }} .
  OPTIONAL {{ ?resourceUri dct:relation ?relatedAssets }} .
  OPTIONAL {{ ?resourceUri dcat:theme ?themeURI }
            { ?themeURI skos:prefLabel ?theme }} .
  OPTIONAL {{ ?resourceUri skos:notation ?externalIdentifier}}

  ?contact vcard:fn ?contactName ;
           vcard:hasEmail ?contactEmail.
  OPTIONAL {{?contact vcard:hasTelephone ?contactTelephone}}
  OPTIONAL {{?contact vcard:hasAddress ?contactAddress}}
}}