PREFIX text: <http://jena.apache.org/text#>
PREFIX dcat: <http://www.w3.org/ns/dcat#>
PREFIX dct: <http://purl.org/dc/terms/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX cddo_asset: <http://marketplace.cddo.gov.uk/asset/>
PREFIX cddo_graph: <http://marketplace.cddo.gov.uk/graph/>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#> 

SELECT ?resourceUri ?identifier ?type ?title ?description ?organisation 
        ?catalogueCreated ?catalogueModified ?created ?issued ?modified 
        ?summary ?serviceType ?creator ?mediaType ?mediaTypeLabel ?theme
FROM cddo_graph:assets
WHERE {{
    ?resourceUri text:query "$q" ;
        dct:identifier ?identifier ;
        a ?typeURI ;
        dct:title ?title ;
        dct:description ?description ;
        dct:publisher ?organisation ;
        cddo_asset:created ?catalogueCreated ;
        cddo_asset:modified ?catalogueModified ;
        .
    ?typeURI rdfs:label ?type .
    OPTIONAL {{ ?resourceUri dcat:distribution ?distribution }
              { ?distribution dcat:mediaType ?mediaTypeUri }
              { ?mediaTypeUri rdfs:label  ?mediaType }
              OPTIONAL {{ ?mediaTypeUri skos:prefLabel ?mediaTypeLabel }}} .
    OPTIONAL {{ ?resourceUri dct:creator ?creator }} .
    OPTIONAL {{ ?resourceUri dct:created ?created }} .
    OPTIONAL {{ ?resourceUri dct:issued ?issued }} .
    OPTIONAL {{ ?resourceUri dct:modified ?modified }} .
    OPTIONAL {{ ?resourceUri rdfs:comment ?summary }} .
    OPTIONAL {{ ?resourceUri dct:type ?serviceType }} .
    OPTIONAL {{ ?resourceUri dcat:theme ?themeURI }
              {?themeURI skos:prefLabel ?theme }} .
}}