PREFIX cddo_user: <http://marketplace.cddo.gov.uk/user/>
PREFIX cddo_graph: <http://marketplace.cddo.gov.uk/graph/>

WITH cddo_graph:users
INSERT {
  cddo_user:$user_id cddo_user:role ?toAdd.
}
WHERE {
  VALUES ?toAdd { $to_add }
}