PREFIX schema: <http://schema.org/>
PREFIX adms: <https://www.w3.org/ns/adms#>
PREFIX dct: <http://purl.org/dc/terms/>
PREFIX dcat: <http://www.w3.org/ns/dcat#>
PREFIX vcard: <http://www.w3.org/2006/vcard/ns#>
PREFIX cddo: <http://marketplace.cddo.gov.uk#>
PREFIX cddo_user: <http://marketplace.cddo.gov.uk/user/>
PREFIX cddo_graph: <http://marketplace.cddo.gov.uk/graph/>

SELECT ?requestId ?assetTitle ?publisherContactName ?publisherContactEmail ?requesterId ?requesterEmail ?requestingOrg ?status ?received ?sharedata ?decisionDate
FROM cddo_graph:shares
FROM cddo_graph:assets
FROM cddo_graph:users
WHERE {
	?asset	dct:publisher "$org" ;
  			dct:identifier ?assetId ;
			dct:title ?assetTitle ;
			dcat:contactPoint ?contact .

	?contact vcard:fn ?publisherContactName ;
			 vcard:hasEmail ?publisherContactEmail .	
	
	?share 	cddo:asset ?assetId ;
			cddo:sharedata ?sharedata ;
			dct:identifier ?requestId ;
			adms:status ?status ;
			dct:modified ?received ;
			cddo:user ?requesterId .
	
	OPTIONAL {{ ?share cddo:decisionDate ?decisionDate . }}

	?user dct:identifier ?requesterId ;
		  vcard:hasEmail ?requesterEmail ;
		  schema:memberOf ?requestingOrg .

	FILTER(?status NOT IN ("NOT STARTED", "IN PROGRESS"))

}