PREFIX adms: <https://www.w3.org/ns/adms#>
PREFIX cddo: <http://marketplace.cddo.gov.uk#>
PREFIX cddo_share: <http://marketplace.cddo.gov.uk/share/>
PREFIX cddo_graph: <http://marketplace.cddo.gov.uk/graph/>

WITH cddo_graph:shares
DELETE {
    cddo_share:$request_id  cddo:reviewNotes ?notes ;
                            adms:status ?status .
}
INSERT {
    cddo_share:$request_id cddo:reviewNotes "$notes" ;
                           adms:status "IN REVIEW" .
}
WHERE {
    OPTIONAL{ cddo_share:$request_id cddo:reviewNotes ?notes } .
    OPTIONAL{ cddo_share:$request_id adms:status ?status } .
}